# Generated by Django 4.1.4 on 2022-12-22 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event_address',
            name='Host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Event_address', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='Address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.event_address'),
        ),
        migrations.AddField(
            model_name='event',
            name='Genre',
            field=models.ManyToManyField(related_name='Genres', to='services.genre'),
        ),
        migrations.AddField(
            model_name='event',
            name='Host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='Image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Images', to='services.event_images'),
        ),
    ]
